### ISSUE TITLE
Cool!

### ISSUE THREAD

**Issue by johnrichardrinehart** [tmountain/uchess#6]
Really cool little application! Thanks for sharing it with all of us. I just played a few games :smile: .

I couldn't find a way to change the default board size (in pixels? or font size?) in the configuration. Is there a way to do this [besides scaling my terminal emulator's font size](https://sw.kovidgoyal.net/kitty/conf/#font-sizes) (I'm using <kbd>Ctrl-shift-=</kbd> to increase font size to implicitly increase the board size).

**Comment by tmountain** [comment]
Hi John,

Thanks for the positive feedback! Font sizes are terminal specific, so you are doing it the right way by using your terminal emulator. There's nothing (to my knowledge) in tcell (the underlying terminal package) to adjust font sizes, etc.

Best,
Travis
